### ISSUE TITLE
MassTransit

### ISSUE THREAD

**Issue by derekbking** [sftpgo/sftpgo-plugin-pubsub#2]
Does this plugin support MassTransit? I am able to publish to a Rabbit queue successfully, but I don't see any easy way to conform to MassTransit's [interoperability standards](https://masstransit-project.com/architecture/interoperability.html). I believe this plugin itself would need to support the format required by MassTransit.

**Comment by drakkan** [comment]
Hi, 

this is not supported. I don't plan to work on this myself sorry. A patch is welcome. 
You can also receive SFTPGo events via HTTP [hooks](https://github.com/drakkan/sftpgo/blob/main/docs/custom-actions.md)

**Comment by derekbking** [comment]
Thank you, we may submit a patch in the future for this. HTTP hooks are sufficient for the time being. I just wanted to make sure I wasn't missing any built in ways of using MassTransit.
