### ISSUE TITLE
How to use this plugin when install SFTPGo as a windows service? 

### ISSUE THREAD

**Issue by daniel-007** [sftpgo/sftpgo-plugin-pubsub#3]
when i run the windows service, i got the log Message as below:

{"level":"debug","time":"2022-07-29T16:56:59.896","sender":"plugins","message":"initialize"}
{"level":"debug","time":"2022-07-29T16:56:59.919","sender":"plugins","message":"no match for plugin process D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe"}
{"level":"debug","time":"2022-07-29T16:56:59.919","sender":"plugins","message":"create new notifier plugin \"D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe\""}
{"level":"info","time":"2022-07-29T16:56:59.919","sender":"plugins.notifier","message":"configuring client automatic mTLS"}
{"level":"debug","time":"2022-07-29T16:56:59.937","sender":"plugins.notifier","path":"D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe","args":"[D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe nats://topic-1 sftp-service]","message":"starting plugin"}
{"level":"debug","time":"2022-07-29T16:56:59.942","sender":"plugins.notifier","path":"D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe","pid":"2428","message":"plugin started"}
{"level":"debug","time":"2022-07-29T16:56:59.942","sender":"plugins.notifier","path":"D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe","message":"waiting for RPC address"}
{"level":"info","time":"2022-07-29T16:57:00.041","sender":"plugins.notifier.sftpgo-plugin-pubsub.exe","message":"[INFO]  starting sftpgo-plugin-pubsub: version=1.0.3-b7fc623-2022-06-04T08:08:40Z topic=nats://topic-1 instance id=sftp-service"}
{"level":"error","time":"2022-07-29T16:57:00.041","sender":"plugins.notifier.sftpgo-plugin-pubsub.exe","message":"[ERROR] unable to open topic: error=\"open topic nats://topic-1: failed to open default connection: NATS_SERVER_URL environment variable not set\""}
{"level":"debug","time":"2022-07-29T16:57:00.042","sender":"plugins","message":"unable to get rpc client for plugin \"D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe\": Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}
{"level":"warn","time":"2022-07-29T16:57:00.042","sender":"plugins","message":"unable to create notifier plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol., config {Type:notifier NotifierOptions:{FsEvents:[download upload] ProviderEvents:[add delete] ProviderObjects:[user admin api_key] RetryMaxTime:60 RetryQueueMaxSize:1000} KMSOptions:{Scheme: EncryptedStatus:} AuthOptions:{Scope:0} Cmd:D:/apps/FTPServer/SFTPGo/plugins/sftpgo-plugin-pubsub.exe Args:[nats://topic-1 sftp-service] SHA256Sum: AutoMTLS:true kmsID:0}"}
{"level":"error","time":"2022-07-29T16:57:00.042","sender":"service","message":"unable to initialize plugin system: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}

**Comment by drakkan** [comment]
Hi,

the logs seem quite clear

```
{"level":"error","time":"2022-07-29T16:57:00.041","sender":"plugins.notifier.sftpgo-plugin-pubsub.exe","message":"[ERROR] unable to open topic: error="open topic nats://topic-1: failed to open default connection: NATS_SERVER_URL environment variable not set""}
```

from the [docs](https://github.com/sftpgo/sftpgo-plugin-pubsub#nats):

> The NATS server is discovered from the NATS_SERVER_URL environment variable (which is something like nats://nats.example.com).

**Comment by daniel-007** [comment]
Yes, I have to set a global environment variable, which may conflict with other applications. Is it possible to obtain through parameters?

**Comment by drakkan** [comment]
You have to set an environment variable, it doesn't have to be global. 

Please don't abuse my free time, I only provide support to project [sponsors/donors](https://github.com/drakkan/sftpgo#sponsors)
