### ISSUE TITLE
Can it support RocketMQ?

### ISSUE THREAD

**Issue by MagicZhenDong** [sftpgo/sftpgo-plugin-pubsub#4]

**Comment by MagicZhenDong** [comment]
I want to use RocketMQ, but there is no direct support available, and I don't know what to do. I have no choice but to ask for your help!

**Comment by drakkan** [comment]
> I want to use RocketMQ, but there is no direct support available, and I don't know what to do. I have no choice but to ask for your help!

Hello, you have 2 choices:

1) write your own plugin to support RocketMQ
2) sponsor the plugin development

I don't plan to support RocketMQ here, sorry.
